Algoritmo "attv3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis 
n: vetor [0..1] de inteiro
tt: inteiro

Inicio
escreva ("qual o primeiro valor?: ")
   leia (n[0])
     escreva ("qual o segundo valor?: ")
        leia (n[1])
        tt<-(n[0]+n[1])
          escreva ("o resultado total é: ",tt)


Fimalgoritmo