Algoritmo "atvv7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis 
v: real
raio: real
altura:real

Inicio
// vOLUME = 3,14159 * RAIO * RAIO * ALTURA.

escreva("qual a altura da lata: ")
  leia(altura)
   escreva("qual o valor do raio da lata: ")
     leia(raio)

     v <- (pi * raio * raio * altura)
       escreva("o valor do volume da lata é:",v)

Fimalgoritmo